# Generated by Apex Orchestrator - characterization test
# module: app.execution.objectives.collapse_startswith
#
# Pins the module's CURRENT behaviour: it asserts only what is honestly
# knowable (it imports; each public callable is callable and runs without
# an obvious error), not a value oracle. Regenerate, do not hand-tune.

import app.execution.objectives.collapse_startswith


def test_collapse_startswith_imports():
    """The collapse_startswith module imports cleanly (smoke test)."""
    assert app.execution.objectives.collapse_startswith is not None
