# Generated by Apex Orchestrator
# task: idea-x.e
# title: Create a first test stub for app/skills/quality_judge.py

import app.skills.quality_judge


def test_quality_judge_imports():
    """The quality_judge module imports cleanly (smoke test)."""
    assert app.skills.quality_judge is not None
