"""The `fortify` lens — the new development operator.

NOTE: the originally-requested `harden` lens already exists in the alphabet
(``Operator("harden", ...)``), so this lens adds the more specific, distinct
semantics the brief describes: take a fragile/edge concern and add the *smallest
deterministic guard* that removes one failure mode under adverse/edge input.
The lens name is ``fortify`` to avoid colliding with the existing ``harden``.
"""

from pathlib import Path

from app.engine.idea_permutation import IdeaPermutationEngine

_LENS = "fortify"


def _project(tmp: Path) -> Path:
    (tmp / "app").mkdir()
    (tmp / "app" / "main.py").write_text("def main():\n    return 1\n")
    (tmp / "app" / "api.py").write_text(
        "import app.main\n\ndef handler():\n    return app.main.main()\n"
    )
    return tmp


def test_fortify_operator_registered_exactly_once():
    # Present once, matches the Operator contract (a `{x}` placeholder), and
    # carries a well-formed weight in the requested ~0.5 range.
    from app.engine.idea_permutation import DEVELOPMENT_OPERATORS

    matches = [op for op in DEVELOPMENT_OPERATORS if op.name == _LENS]
    assert len(matches) == 1
    fortify = matches[0]
    assert "{x}" in fortify.template
    # ~0.5: a focused, self-contained guard lens — same tier as verify/simplify.
    assert 0.45 <= fortify.feasibility <= 0.55
    assert 0.0 <= fortify.feasibility <= 1.0
    # Still a unique name like every sibling.
    names = [op.name for op in DEVELOPMENT_OPERATORS]
    assert len(names) == len(set(names))


def test_fortify_operator_wired_into_hints_and_facets():
    # The lens flows through the same machinery as its siblings: a keyword hint
    # for caveats, a facet vocabulary for the fractal zoom, and a lens scenario.
    from app.engine.idea_permutation import _OPERATOR_HINTS, _FACETS
    from app.engine.counterfactual_generator import _LENS_SCENARIOS

    assert _OPERATOR_HINTS.get(_LENS)            # non-empty keyword hint
    assert _FACETS.get(_LENS)                    # level-1 facet vocabulary
    assert _LENS_SCENARIOS.get(_LENS)            # its own counterfactual scenarios


def test_engine_emits_fortify_lens_idea(tmp_path):
    # Running the engine on a small synthetic project yields at least one idea
    # generated by the `fortify` lens, phrased from its template.
    _project(tmp_path)
    rep = IdeaPermutationEngine(
        {"max_total_ideas": 90, "max_idea_depth": 2, "breadth": 11}, tmp_path
    ).run()
    fortify_ideas = [i for i in rep.ideas if i.operator == _LENS]
    assert fortify_ideas, "expected at least one idea from the fortify lens"
    # Template phrasing reaches the rationale; the title is the composed chain.
    assert any("smallest guard" in i.rationale for i in fortify_ideas)
    assert all("Fortify" in i.title for i in fortify_ideas)
    # The new lens obeys every shared invariant.
    assert all(0.0 <= i.value <= 1.0 for i in fortify_ideas)
    assert all(0.0 <= i.feasibility <= 1.0 for i in fortify_ideas)
    assert all(i.source_facts for i in fortify_ideas)
    assert all(_LENS in i.operator_chain for i in fortify_ideas)


def test_fortify_lens_participates_like_other_operators(tmp_path):
    # It permutes exactly like the siblings: a child's chain extends its
    # parent's by exactly the fortify lens, and never repeats within a branch.
    _project(tmp_path)
    rep = IdeaPermutationEngine(
        {"max_total_ideas": 90, "max_idea_depth": 3, "breadth": 11}, tmp_path
    ).run()
    by_id = {i.id: i for i in rep.ideas}
    fortify_perm = [
        i for i in rep.ideas if i.operator == _LENS and i.kind == "permutation"
    ]
    assert fortify_perm
    for idea in fortify_perm:
        assert len(idea.operator_chain) == len(set(idea.operator_chain))  # no repeat
        if idea.parent_id:
            parent = by_id[idea.parent_id]
            assert idea.operator_chain[:-1] == parent.operator_chain
            assert idea.operator_chain[-1] == _LENS
            assert idea.depth == parent.depth + 1


def test_engine_values_and_feasibility_stay_in_unit_interval(tmp_path):
    # Adding the lens keeps every node's value and feasibility in [0, 1] and
    # roots at novelty 1.0 (the engine-wide invariants).
    _project(tmp_path)
    rep = IdeaPermutationEngine(
        {"max_total_ideas": 90, "max_idea_depth": 3, "breadth": 11}, tmp_path
    ).run()
    assert all(0.0 <= i.value <= 1.0 for i in rep.ideas)
    assert all(0.0 <= i.feasibility <= 1.0 for i in rep.ideas)
    assert all(r.novelty == 1.0 for r in rep.ideas if r.operator == "root")


def test_engine_with_fortify_lens_is_deterministic(tmp_path):
    # Two runs are identical and every produced idea keeps value in [0, 1].
    _project(tmp_path)
    cfg = {"max_total_ideas": 90, "max_idea_depth": 2, "breadth": 11}
    a = IdeaPermutationEngine(cfg, tmp_path).run()
    b = IdeaPermutationEngine(cfg, tmp_path).run()
    assert [i.title for i in a.ideas] == [i.title for i in b.ideas]
    assert all(0.0 <= i.value <= 1.0 for i in a.ideas)


def test_fortify_caveat_stays_on_lens(tmp_path):
    # The hint/scenario keep the fortify caveat interrogating edge/guard
    # failure, not the generic "holds after refactoring" fallback.
    _project(tmp_path)
    rep = IdeaPermutationEngine(
        {"max_total_ideas": 90, "max_idea_depth": 2, "breadth": 11}, tmp_path
    ).run()
    fortify = next(i for i in rep.ideas if i.operator == _LENS)
    joined = " ".join(fortify.caveats).lower()
    assert any(k in joined for k in ("edge", "guard", "boundary", "malformed", "none"))


def test_fortify_facets_zoom_when_enabled(tmp_path):
    # With facets on, a fortify leaf opens into its own self-similar sub-ideas
    # drawn from the lens's facet vocabulary, all in [0, 1].
    _project(tmp_path)
    rep = IdeaPermutationEngine(
        {
            "max_total_ideas": 160,
            "max_idea_depth": 1,
            "breadth": 11,
            "fractal_facets": True,
            "facet_depth": 1,
            "facets_per_idea": 2,
        },
        tmp_path,
    ).run()
    from app.engine.idea_permutation import _FACETS

    fortify_facets = [
        i for i in rep.ideas if i.kind == "facet" and i.operator == _LENS
    ]
    # The lens vocabulary is wired; if budget reaches a fortify leaf, its facets
    # use that vocabulary. (Facets share the budget, so guard the existence.)
    vocab = set(_FACETS[_LENS])
    for f in fortify_facets:
        phrase = [s for s in f.source_facts if s.startswith("facet:")][-1]
        assert phrase.split("facet:", 1)[1].strip() in vocab
        assert 0.0 <= f.value <= 1.0
        assert " :: " in f.subject
