# Generated by Apex Orchestrator - characterization test
# module: app.engine.wilson
#
# Pins the module's CURRENT behaviour. Where the real return value of a
# public function is a simple, reproducible literal it was captured at
# generation time and pinned as a value oracle (assert fn(...) == <value>);
# otherwise it asserts only what is honestly knowable (it imports; the
# callable runs without an obvious error). Regenerate, do not hand-tune.

import app.engine.wilson


def test_wilson_imports():
    """The wilson module imports cleanly (smoke test)."""
    assert app.engine.wilson is not None


def test_wilson_wilson_lower_bound_characterization():
    """Characterize wilson_lower_bound: it returns the captured value on synthesized inputs."""
    fn = app.engine.wilson.wilson_lower_bound
    assert callable(fn)
    # Value oracle: the captured real return value pins behaviour exactly.
    assert fn(0.0, 0.0) == 0.0
