"""Characterization harness pinning ``discover_structured`` byte-for-byte.

Builds a battery of representative ``ProjectProfile`` inputs that exercise
every discovery path (association, triple, confluence), every threshold edge
(support/confidence floors, the confluence-floor and typical-breadth cut),
the truncation slices (assoc[:4], triples[:2], confluence[:2]), and the empty
paths (< 2 tagged modules, profile with no signals). For each it records the
full ``to_dict()`` list — order AND contents — so any drift in the refactor is
caught. Determinism is checked by running each input twice.
"""

from __future__ import annotations

from app.engine.dream_discovery import discover, discover_structured
from app.tools.project_profile import ProjectProfile


def _cases() -> list[ProjectProfile]:
    cases: list[ProjectProfile] = []

    # 0) Empty — fewer than two tagged modules.
    cases.append(ProjectProfile(root="."))

    # 1) A single tagged module — still below the len(tags) < 2 guard once
    #    all signals land on one path.
    cases.append(ProjectProfile(
        root=".",
        security_finding_modules=["app/a.py"],
        untested_modules=["app/a.py"],
    ))

    # 2) Simple association: untested & debt always travel together.
    cases.append(ProjectProfile(
        root=".",
        untested_modules=["app/a.py", "app/b.py"],
        debt_marker_modules=["app/a.py", "app/b.py"],
    ))

    # 3) Association via churn/knowledge mixed-shape fields.
    cases.append(ProjectProfile(
        root=".",
        churn_hotspots=[{"module": "app/a.py", "commits": 9},
                        {"module": "app/b.py", "commits": 8},
                        {"module": "app/quiet.py", "commits": 7}],
        knowledge_risks=[{"module": "app/a.py", "share": 100, "commits": 9},
                         {"module": "app/b.py", "share": 90, "commits": 8}],
    ))

    # 4) Confluence: one broad module, others single-signal.
    cases.append(ProjectProfile(
        root=".",
        security_finding_modules=["app/hot.py"],
        untested_modules=["app/hot.py", "app/x.py"],
        fragile_modules=["app/hot.py"],
        debt_marker_modules=["app/hot.py", "app/y.py"],
    ))

    # 5) Triple rule: A & B co-occurring drag in C.
    cases.append(ProjectProfile(
        root=".",
        security_finding_modules=["app/a.py", "app/b.py", "app/c.py"],
        untested_modules=["app/a.py", "app/b.py", "app/c.py"],
        fragile_modules=["app/a.py", "app/b.py", "app/c.py"],
    ))

    # 6) Rich tangle — exercises truncation slices and tie-breaks. Many tags
    #    on overlapping modules across every field family.
    cases.append(ProjectProfile(
        root=".",
        security_finding_modules=["m1", "m2", "m3"],
        correctness_bug_modules=["m1", "m2"],
        fragile_modules=["m1", "m2", "m3", "m4"],
        untested_modules=["m1", "m2", "m3", "m4", "m5"],
        critical_untested_modules=["m1", "m2"],
        hotspot_modules=["m2", "m3"],
        debt_marker_modules=["m1", "m3", "m4"],
        shallow_tested_modules=["m2", "m5"],
        modernizable_modules=["m4", "m5"],
        mutable_default_modules=["m1"],
        dependency_hubs=["m3"],
        symbol_hubs=["m2"],
        sensitive_paths=["m1"],
        churn_hotspots=[{"module": "m1", "commits": 5},
                        {"module": "m2", "commits": 4}],
        knowledge_risks=[{"module": "m1", "share": 99},
                         {"module": "m3", "share": 80}],
        hotspot_functions=[{"module": "m4"}, {"module": "m2"}],
        change_coupling=[{"a": "m1", "b": "m2"}, {"a": "m3", "b": "m5"}],
    ))

    # 7) Empty-ish dict entries and falsy modules — guards in add().
    cases.append(ProjectProfile(
        root=".",
        churn_hotspots=[{"module": ""}, {"nope": "x"}],
        knowledge_risks=[{"module": ""}],
        change_coupling=[{"a": "", "b": ""}],
        untested_modules=["", "app/u.py", "app/v.py"],
        debt_marker_modules=["app/u.py", "app/v.py"],
    ))

    # 8) Two modules exactly at MIN_SUPPORT with confidence right at floor.
    cases.append(ProjectProfile(
        root=".",
        untested_modules=["p1", "p2", "p3", "p4"],
        debt_marker_modules=["p1", "p2"],
    ))

    return cases


# A golden snapshot captured from the ORIGINAL implementation at base HEAD.
# Generated by running this module's _dump() against the pre-refactor source.
EXPECTED = None  # filled in below


def _dump(profile: ProjectProfile) -> list[dict]:
    return [d.to_dict() for d in discover_structured(profile)]


def test_characterization_matches_golden():
    from tests._dream_discovery_golden import GOLDEN
    cases = _cases()
    assert len(cases) == len(GOLDEN)
    for i, (profile, expected) in enumerate(zip(cases, GOLDEN)):
        got = _dump(profile)
        assert got == expected, f"case {i} drifted:\n got={got}\n exp={expected}"


def test_determinism_same_input_same_output():
    for profile in _cases():
        assert _dump(profile) == _dump(profile)


def test_discover_text_matches_structured():
    for profile in _cases():
        assert discover(profile) == [d["text"] for d in _dump(profile)]
