# Generated by Apex Orchestrator
# task: idea-x.d.c
# title: Create a test stub covering smctrader/liquidity.py

import smctrader.liquidity


def test_liquidity_imports():
    """The liquidity module imports cleanly (smoke test)."""
    assert smctrader.liquidity is not None


def test_liquidity_callable_contracts():
    """Public callables run on synthesized inputs; annotated return types are checked."""
    assert isinstance(smctrader.liquidity.equal_levels([]), list)
    assert isinstance(smctrader.liquidity.find_sweeps([]), list)
