# Generated by Apex Orchestrator
# task: idea-x.e.c
# title: Create a test stub covering smctrader/data.py

import smctrader.data


def test_data_imports():
    """The data module imports cleanly (smoke test)."""
    assert smctrader.data is not None


def test_data_callable_contracts():
    """Public callables run on synthesized inputs; annotated return types are checked."""
    assert isinstance(smctrader.data.synthetic_candles(), list)
