from __future__ import annotations

import ast
import textwrap
from pathlib import Path

from ..result import SemanticPatchResult


def _find_source_module(root: Path, module_name: str) -> Path | None:
    """Locate the source file for ``module_name`` (deterministically, not a test)."""
    skip = {"__pycache__", ".git", ".apex", ".venv", "venv", "tests", "test"}
    matches = [
        p for p in sorted(root.rglob(f"{module_name}.py"))
        if not any(part in skip for part in p.relative_to(root).parts)
    ]
    return matches[0] if matches else None


def _dotted_name(root: Path, source: Path) -> str:
    """Importable dotted path for a source file run with the project root on sys.path."""
    rel = source.relative_to(root).with_suffix("")
    return ".".join(rel.parts)


# Safe "zero value" literal to synthesize for a required argument of each type.
_ARG_SAMPLE = {
    "int": "0", "float": "0.0", "bool": "False", "complex": "0j",
    "str": "''", "bytes": "b''", "bytearray": "bytearray()",
    "list": "[]", "dict": "{}", "tuple": "()", "set": "set()", "frozenset": "frozenset()",
}
_TYPING_CONTAINER = {"List": "list", "Dict": "dict", "Tuple": "tuple", "Set": "set",
                     "FrozenSet": "frozenset", "Sequence": "list", "Mapping": "dict"}
# Return types we assert with isinstance. int/float/complex are omitted: the
# numeric tower (a bool is an int, an int satisfies a float annotation, ...)
# makes those checks brittle, so for numeric returns we only assert no-crash.
_RET_ISINSTANCE = {"str", "bytes", "bytearray", "list", "dict", "tuple", "set", "frozenset", "bool"}


def _union_has_none(node: ast.AST) -> bool:
    parts: list[ast.AST] = []
    def walk(n: ast.AST) -> None:
        if isinstance(n, ast.BinOp) and isinstance(n.op, ast.BitOr):
            walk(n.left)
            walk(n.right)
        else:
            parts.append(n)
    walk(node)
    return any(isinstance(p, ast.Constant) and p.value is None for p in parts)


def _arg_literal(ann: ast.expr | None) -> str | None:
    """A safe sample literal for an annotated argument, or None if not synthesizable."""
    if ann is None:
        return None
    if isinstance(ann, ast.Constant) and ann.value is None:
        return "None"
    if isinstance(ann, ast.BinOp) and isinstance(ann.op, ast.BitOr):
        return "None" if _union_has_none(ann) else None  # X | None -> None is safe
    if isinstance(ann, ast.Subscript) and isinstance(ann.value, ast.Name):
        head = ann.value.id
        if head == "Optional":
            return "None"
        base = _TYPING_CONTAINER.get(head, head)
        return _ARG_SAMPLE.get(base)
    if isinstance(ann, ast.Name):
        return _ARG_SAMPLE.get(ann.id)
    return None


def _ret_isinstance(ann: ast.expr | None) -> str | None:
    """The builtin type to assert the return value is an instance of, or None."""
    if isinstance(ann, ast.Subscript) and isinstance(ann.value, ast.Name):
        base = _TYPING_CONTAINER.get(ann.value.id, ann.value.id)
        return base if base in _RET_ISINSTANCE else None
    if isinstance(ann, ast.Name) and ann.id in _RET_ISINSTANCE:
        return ann.id
    return None


def _call_specs(tree: ast.Module) -> list[tuple[str, str, str | None]]:
    """Public sync functions we can safely call, with synthesized args.

    Returns ``(name, call_args, return_type_or_None)`` for each function whose
    every *required* parameter has a synthesizable annotation (defaulted params
    are omitted; ``*args``/``**kwargs`` default to empty). Async functions are
    excluded — a bare call returns a coroutine, not the annotated value.
    """
    specs: list[tuple[str, str, str | None]] = []
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef) or node.name.startswith("_"):
            continue
        a = node.args
        positional = a.posonlyargs + a.args
        n_required = len(positional) - len(a.defaults)
        literals: list[str] = []
        ok = True
        for p in positional[:n_required]:
            lit = _arg_literal(p.annotation)
            if lit is None:
                ok = False
                break
            literals.append(lit)
        if not ok:
            continue
        for kwarg, kdef in zip(a.kwonlyargs, a.kw_defaults):
            if kdef is None:  # required keyword-only arg
                lit = _arg_literal(kwarg.annotation)
                if lit is None:
                    ok = False
                    break
                literals.append(f"{kwarg.arg}={lit}")
        if not ok:
            continue
        specs.append((node.name, ", ".join(literals), _ret_isinstance(node.returns)))
    return sorted(specs)[:12]


def _skip_stub(rel_path: str, module_name: str, title: str, task_id: str) -> SemanticPatchResult:
    content = textwrap.dedent(
        f"""\
        # Generated by Apex Orchestrator
        # task: {task_id}
        # title: {title}

        import pytest


        @pytest.mark.skip(reason="Apex stub: implement tests for {module_name}")
        def test_{module_name}_exists():
            \"\"\"Placeholder test for the {module_name} module.

            Replace this stub: import the module under test and assert
            on its public behavior. The skip marker keeps the suite green
            until a real assertion is written.
            \"\"\"
            raise NotImplementedError("Implement tests for {module_name}")
        """
    )
    return SemanticPatchResult(
        patch_requests=[{"path": rel_path, "new_content": content, "expected_old_content": None}],
        transform_type="create_test_stub",
        rationale=[f"Created missing test stub at {rel_path}."],
    )


def try_create_stub(root: Path, rel_path: str, title: str, task_id: str) -> SemanticPatchResult | None:
    if not (rel_path.endswith(".py") and "test_" in rel_path):
        return None
    parts = Path(rel_path).parts
    if not (len(parts) >= 2 and parts[0] == "tests"):
        return None
    module_name = parts[1].replace("test_", "").replace(".py", "")

    # Locate the real source module so the generated test actually exercises it.
    source = _find_source_module(root, module_name)
    if source is None:
        return _skip_stub(rel_path, module_name, title, task_id)
    try:
        tree = ast.parse(source.read_text(encoding="utf-8", errors="ignore"))
    except (OSError, SyntaxError):
        return _skip_stub(rel_path, module_name, title, task_id)

    dotted = _dotted_name(root, source)
    specs = _call_specs(tree)

    lines = [
        "# Generated by Apex Orchestrator",
        f"# task: {task_id}",
        f"# title: {title}",
        "",
        f"import {dotted}",
        "",
        "",
        f"def test_{module_name}_imports():",
        f'    """The {module_name} module imports cleanly (smoke test)."""',
        f"    assert {dotted} is not None",
    ]
    asserts = sum(1 for _n, _a, ret in specs if ret)
    if specs:
        lines += [
            "",
            "",
            f"def test_{module_name}_callable_contracts():",
            '    """Public callables run on synthesized inputs; annotated return types are checked."""',
        ]
        for name, call_args, ret in specs:
            if ret:
                lines.append(f"    assert isinstance({dotted}.{name}({call_args}), {ret})")
            else:
                lines.append(f"    {dotted}.{name}({call_args})")
    content = "\n".join(lines) + "\n"

    if asserts:
        note = f"({len(specs)} callable(s) exercised, {asserts} return-type contract(s) asserted)"
    elif specs:
        note = f"({len(specs)} callable(s) exercised)"
    else:
        note = "(import smoke test)"
    return SemanticPatchResult(
        patch_requests=[{"path": rel_path, "new_content": content, "expected_old_content": None}],
        transform_type="create_test_stub",
        rationale=[f"Created a real characterization test at {rel_path} for {dotted} {note}."],
    )
