from __future__ import annotations

import ast
import textwrap
from pathlib import Path

from ..result import SemanticPatchResult


def _find_source_module(root: Path, module_name: str) -> Path | None:
    """Locate the source file for ``module_name`` (deterministically, not a test)."""
    skip = {"__pycache__", ".git", ".apex", ".venv", "venv", "tests", "test"}
    matches = [
        p for p in sorted(root.rglob(f"{module_name}.py"))
        if not any(part in skip for part in p.relative_to(root).parts)
    ]
    return matches[0] if matches else None


def _dotted_name(root: Path, source: Path) -> str:
    """Importable dotted path for a source file run with the project root on sys.path."""
    rel = source.relative_to(root).with_suffix("")
    return ".".join(rel.parts)


def _zero_arg_functions(tree: ast.Module) -> list[str]:
    """Public top-level functions callable with no arguments (smoke-testable)."""
    out: list[str] = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name.startswith("_"):
            continue
        a = node.args
        # Every positional / pos-only / kw-only parameter must have a default,
        # and there must be no required *args. (**kwargs is fine — it defaults
        # to empty.) Then `func()` is a safe call.
        required_pos = len(a.posonlyargs) + len(a.args) - len(a.defaults)
        required_kw = sum(1 for d in a.kw_defaults if d is None)
        if required_pos <= 0 and required_kw == 0 and a.vararg is None:
            out.append(node.name)
    return sorted(out)


def _skip_stub(rel_path: str, module_name: str, title: str, task_id: str) -> SemanticPatchResult:
    content = textwrap.dedent(
        f"""\
        # Generated by Apex Orchestrator
        # task: {task_id}
        # title: {title}

        import pytest


        @pytest.mark.skip(reason="Apex stub: implement tests for {module_name}")
        def test_{module_name}_exists():
            \"\"\"Placeholder test for the {module_name} module.

            Replace this stub: import the module under test and assert
            on its public behavior. The skip marker keeps the suite green
            until a real assertion is written.
            \"\"\"
            raise NotImplementedError("Implement tests for {module_name}")
        """
    )
    return SemanticPatchResult(
        patch_requests=[{"path": rel_path, "new_content": content, "expected_old_content": None}],
        transform_type="create_test_stub",
        rationale=[f"Created missing test stub at {rel_path}."],
    )


def try_create_stub(root: Path, rel_path: str, title: str, task_id: str) -> SemanticPatchResult | None:
    if not (rel_path.endswith(".py") and "test_" in rel_path):
        return None
    parts = Path(rel_path).parts
    if not (len(parts) >= 2 and parts[0] == "tests"):
        return None
    module_name = parts[1].replace("test_", "").replace(".py", "")

    # Locate the real source module so the generated test actually exercises it.
    source = _find_source_module(root, module_name)
    if source is None:
        return _skip_stub(rel_path, module_name, title, task_id)
    try:
        tree = ast.parse(source.read_text(encoding="utf-8", errors="ignore"))
    except (OSError, SyntaxError):
        return _skip_stub(rel_path, module_name, title, task_id)

    dotted = _dotted_name(root, source)
    smoke = _zero_arg_functions(tree)

    lines = [
        "# Generated by Apex Orchestrator",
        f"# task: {task_id}",
        f"# title: {title}",
        "",
        "import importlib",
        "",
        "",
        f"def test_{module_name}_imports():",
        f'    """The {module_name} module imports cleanly (smoke test)."""',
        f'    mod = importlib.import_module("{dotted}")',
        "    assert mod is not None",
    ]
    if smoke:
        lines += [
            "",
            "",
            f"def test_{module_name}_zero_arg_callables_run():",
            '    """Public no-argument callables run without raising (characterization)."""',
            f'    mod = importlib.import_module("{dotted}")',
        ]
        for fn in smoke:
            lines.append(f"    mod.{fn}()")
    content = "\n".join(lines) + "\n"

    note = f"({len(smoke)} no-arg callable(s) exercised)" if smoke else "(import smoke test)"
    return SemanticPatchResult(
        patch_requests=[{"path": rel_path, "new_content": content, "expected_old_content": None}],
        transform_type="create_test_stub",
        rationale=[f"Created a real characterization test at {rel_path} for {dotted} {note}."],
    )
