from __future__ import annotations

import textwrap

from pathlib import Path

from ..result import SemanticPatchResult


def try_create_stub(root: Path, rel_path: str, title: str, task_id: str) -> SemanticPatchResult | None:
    if "test_" in rel_path and rel_path.endswith(".py"):
        parts = Path(rel_path).parts
        if len(parts) >= 2 and parts[0] == "tests":
            module_name = parts[1].replace("test_", "").replace(".py", "")
            content = textwrap.dedent(
                f"""\
                # Generated by Apex Orchestrator
                # task: {task_id}
                # title: {title}

                import pytest


                def test_{module_name}_exists():
                    assert True, "stub test for {module_name}"
                """
            )
            return SemanticPatchResult(
                patch_requests=[{
                    "path": rel_path,
                    "new_content": content,
                    "expected_old_content": None,
                }],
                transform_type="create_test_stub",
                rationale=[f"Created missing test stub at {rel_path}."],
            )
    return None
