from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class IdeaNode(BaseModel):
    """A single autonomous development direction in the idea tree.

    Generated by the IdeaPermutationEngine. Every idea is traceable to concrete
    project facts (``source_facts``) and to the development lens that produced it
    (``operator``).
    """

    id: str
    title: str
    subject: str = ""
    rationale: str = ""
    branch_path: str = ""
    depth: int = 0
    parent_id: str | None = None
    source_facts: list[str] = Field(default_factory=list)
    operator: str = "root"
    operator_chain: list[str] = Field(default_factory=list)

    relevance: float = 1.0
    novelty: float = 1.0
    feasibility: float = 0.5
    value: float = 0.0
    caveats: list[str] = Field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump()


class IdeaTreeReport(BaseModel):
    """The result of an idea-permutation run."""

    objective: str = ""
    project_root: str = ""
    ideas: list[IdeaNode] = Field(default_factory=list)
    branch_map: dict[str, str] = Field(default_factory=dict)
    stats: dict[str, Any] = Field(default_factory=dict)

    def roots(self) -> list[IdeaNode]:
        return [i for i in self.ideas if i.depth == 0]

    def children_of(self, parent_id: str) -> list[IdeaNode]:
        return [i for i in self.ideas if i.parent_id == parent_id]
