from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class IdeaNode(BaseModel):
    """A single autonomous development direction in the idea tree.

    Generated by the IdeaPermutationEngine. Every idea is traceable to concrete
    project facts (``source_facts``) and to the development lens that produced it
    (``operator``).
    """

    id: str
    title: str
    subject: str = ""
    rationale: str = ""
    branch_path: str = ""
    depth: int = 0
    parent_id: str | None = None
    source_facts: list[str] = Field(default_factory=list)
    operator: str = "root"
    operator_chain: list[str] = Field(default_factory=list)
    # How this idea was produced: "permutation" (operator lens chain),
    # "synthesis" (combined lenses), or "pair" (module-pair from the dep graph).
    kind: str = "permutation"

    relevance: float = 1.0
    novelty: float = 1.0
    feasibility: float = 0.5
    value: float = 0.0
    caveats: list[str] = Field(default_factory=list)
    # Concrete loci WITHIN a module-level idea: the riskiest function(s) the idea
    # should act on first, so "Untangle module X" names a function + line +
    # metric instead of just the file. Each anchor is a dict shaped
    # ``{"module": str, "symbol": str, "line": int, "metric": str}`` where
    # ``metric`` is a short grounded string (e.g. "cyclomatic 18"). Additive and
    # default-empty: ideas with no function-grain data carry no anchors, keeping
    # every existing idea set and render byte-identical.
    anchors: list[dict] = Field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump()


class IdeaTreeReport(BaseModel):
    """The result of an idea-permutation run."""

    objective: str = ""
    project_root: str = ""
    ideas: list[IdeaNode] = Field(default_factory=list)
    branch_map: dict[str, str] = Field(default_factory=dict)
    stats: dict[str, Any] = Field(default_factory=dict)

    def roots(self) -> list[IdeaNode]:
        return [i for i in self.ideas if i.depth == 0]

    def children_of(self, parent_id: str) -> list[IdeaNode]:
        return [i for i in self.ideas if i.parent_id == parent_id]


class ActionStep(BaseModel):
    """A concrete, reviewable action derived from a development idea.

    The bridge never executes — it proposes what acting on an idea branch
    would concretely mean, mapping it to a known transform when one exists.
    """

    branch_path: str
    title: str
    operator: str
    subject: str
    action_type: str
    target: str = ""
    description: str = ""
    executable: bool = False
    value: float = 0.0
    source_facts: list[str] = Field(default_factory=list)
    patch_preview: dict[str, Any] | None = None
    # Roadmap phase this step belongs to, when planned via a roadmap
    # (Stabilize/Secure/Evolve/Refine). Empty for value-ordered plans.
    phase: str = ""

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump()


class ActionPlan(BaseModel):
    """An ordered, supervised action plan derived from an idea tree."""

    objective: str = ""
    project_root: str = ""
    mode: str = "supervised"
    steps: list[ActionStep] = Field(default_factory=list)
    stats: dict[str, Any] = Field(default_factory=dict)

    def executable_steps(self) -> list[ActionStep]:
        return [s for s in self.steps if s.executable]

